version: 2
jobs:   
    build:
        working_directory: ~/case_microservice
        docker:
            - image: python:3.6.0
        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
            - run: 
                name: Install Python deps in a venv
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements/dev.txt
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
                paths:
                    - "venv"
            # run tests
            - run:
                command: |
                   . venv/bin/activate
                   python -m pytest --cov=Case
            # run linter
            - run:
                command: |
                   . venv/bin/activate
                   flake8 Case/
            # build docker image
            - setup_remote_docker
            - run:
                name: Install docker client
                command: |
                    set -x
                    VER="17.03.0-ce"
                    curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
                    tar -xz -C /tmp -f /tmp/docker-$VER.tgz
                    mv /tmp/docker/* /usr/bin
            - run:
                name: Build docker image
                command: |
                    TAG=0.1.$CIRCLE_BUILD_NUM
                    docker build -t circleci/case-microservice:$TAG .
